name: MobLoot
main: net.mcbat.MobLoot.MobLoot
author: Steven Mattera
website: http://mc-bat.net
version: 3.01
commands:
    mobloot:
        aliases: [ml, loot]
        description: Commands for manipulating loot.
        usage: |
            /<command> set <world> <mob> <item,item,...> - Edit mob loot.
            /<command> load - Reload the configuration from disk.
            /<command> save - Save the configuration to disk.
permissions:
    mobloot.commands.*:
        description: Allows use of all MobLoot commands.
        children:
            mobloot.commands.set: true
            mobloot.commands.load: true
            mobloot.commands.save: true
    mobloot.commands.set:
        description: Allows use of /mobloot set.
    mobloot.commands.load:
        description: Allows use of /mobloot load.
    mobloot.commands.save:
        description: Allows use of /mobloot save.