name: MobLoot
main: net.mcbat.MobLoot.MobLoot
version: 2.01
website: http://mc-bat.net
author: Steven Mattera
description: Simple plugin for modifying the loot that drops off mobs.
commands:
    mobloot:
        description: View and edit drops.
        aliases: [ml]
        permission: MobLoot.Admin.ml
        usage: /<command> <world> <mob> <item,item,...>
    moblootsave:
        description: Save the config file.
        aliases: [mls]
        permission: MobLoot.Admin.mls
        usage: /<command>
    moblootload:
        description: Load the config file.
        aliases: [mll]
        permission: MobLoot.Admin.mll
        usage: /<command>    